#!/usr/bin/env python
import os
import sys

if __name__ == "__main__":
    from django.core import management

    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "katubi.settings")

    management.execute_from_command_line(sys.argv)
