[tool.poetry]
name = "katubi"
version = "0"
description = ""
authors = ["Samuel Searles-Bryant <sam@samueljsb.co.uk>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.1.7"
envparse = "^0.2.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
invoke = "^1.5.0"
isort = "^5.8.0"
mypy = "^0.812"
pytest = "^6.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
