[tool.poetry]
name = "katubi"
version = "0"
description = ""
authors = ["Samuel Searles-Bryant <sam@samueljsb.co.uk>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.2"
djangorestframework = "^3.12.4"
envparse = "^0.2.0"
psycopg2 = "^2.8.6"
requests = "^2.25.1"
sentry-sdk = "^1.1.0"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
django-stubs = "^1.7.0"
flake8 = "^3.9.2"
invoke = "^1.5.0"
isort = "^5.8.0"
mypy = "^0.812"
pytest = "^6.2.4"
responses = "^0.13.3"
factory-boy = "^3.2.0"
pytest-django = "^4.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
