# Generated by Django 3.2.5 on 2021-07-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0002_author_name_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(default="", max_length=13)),
                ("cover_image_url", models.URLField(default="")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="books.book"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="volume",
            constraint=models.UniqueConstraint(
                condition=models.Q(("isbn", ""), _negated=True),
                fields=("isbn",),
                name="unique_isbn",
            ),
        ),
    ]
