# Generated by Django 3.2.5 on 2021-07-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volumes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="cover_image_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="volume",
            name="isbn",
            field=models.CharField(blank=True, default="", max_length=13),
        ),
    ]
